### ISSUE TITLE
Event decor not here

### ISSUE THREAD

**Issue by TristanAUA** [Notuom/pikmin-bloom-checklist#3]
The lunar new year decor and Christmas decor's are not here

**Comment by Notuom** [comment]
Thanks for the feedback!

The winter stickers should be easy enough to add.

I haven't played recently so I didn't know about the Lunar New Year event. Looks like it's only available for certain types of Pikmin colors, which complicates things since the current code doesn't support that, but perhaps we can deal with that in a later update after adding it as a regular decor.

**Comment by TristanAUA** [comment]
Yes it comes only in red,blue and yellow

**Comment by Notuom** [comment]
Thanks @TristanAUA . I added a few new features in 1.3.0 including the holidays and lunar new year decor.
